services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=retailtrack-api
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
