FROM node:16-alpine

WORKDIR /app

# Instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar el código fuente
COPY . .

EXPOSE 3000

# Ejecutar en modo desarrollo
CMD ["npm", "run", "dev"]
